# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  geolite2-asn = {
    pname = "geolite2-asn";
    version = "2026.08.07";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2026.08.07/GeoLite2-ASN.mmdb";
      sha256 = "sha256-DiASrAbyakgwI7n9mTPEWNPRqB9d1DmPMs8CrPAGW88=";
    };
  };
  geolite2-city = {
    pname = "geolite2-city";
    version = "2026.08.07";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2026.08.07/GeoLite2-City.mmdb";
      sha256 = "sha256-XDIgbNmmfTuJlejKAQGRqALpywbTwImWPwi1Xesb2SE=";
    };
  };
  geolite2-country = {
    pname = "geolite2-country";
    version = "2026.08.07";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2026.08.07/GeoLite2-Country.mmdb";
      sha256 = "sha256-tPYk4UEcKHAdckUDuNFe1Jl95wy26gXW8Rv1cupVIkA=";
    };
  };
  sing-box-beta = {
    pname = "sing-box-beta";
    version = "1.14.0-beta.12";
    src = fetchurl {
      url = "https://github.com/SagerNet/sing-box/archive/v1.14.0-beta.12.tar.gz";
      sha256 = "sha256-yeM5/zAdJGz5pZq1EMSfsBGkLCv3yzhy20dvXEAYWJM=";
    };
  };
}
