# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  geolite2-asn = {
    pname = "geolite2-asn";
    version = "2026.08.13";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2026.08.13/GeoLite2-ASN.mmdb";
      sha256 = "sha256-CKvpSFlyWmOKtmjQzMH6EFFrDZYjuwCY2vZOwifTNic=";
    };
  };
  geolite2-city = {
    pname = "geolite2-city";
    version = "2026.08.13";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2026.08.13/GeoLite2-City.mmdb";
      sha256 = "sha256-RkglNZhzRtCWngfdDfwDmZxC96tY+5PFBptdvv5bMMY=";
    };
  };
  geolite2-country = {
    pname = "geolite2-country";
    version = "2026.08.13";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2026.08.13/GeoLite2-Country.mmdb";
      sha256 = "sha256-tqUl2P/XYotZoceFMmSTeuOiNjLe6+2dquLr/7+HYmU=";
    };
  };
  sing-box-beta = {
    pname = "sing-box-beta";
    version = "1.14.0-beta.14";
    src = fetchurl {
      url = "https://github.com/SagerNet/sing-box/archive/v1.14.0-beta.14.tar.gz";
      sha256 = "sha256-jrv7b47IU4fJqAw1cf9KRkZTtYO7KtHqqeuJ3A+BLh8=";
    };
  };
}
