# This file was generated by nvfetcher, please do not modify it manually.
{fetchurl}: {
  geolite2-asn = {
    pname = "geolite2-asn";
    version = "2026.08.01";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2026.08.01/GeoLite2-ASN.mmdb";
      hash = "sha256-3c7BRePD6gY4nYhyNY2mU/kIbe3rvX0Ptcdb4nbZRB4=";
    };
  };
  geolite2-city = {
    pname = "geolite2-city";
    version = "2026.08.01";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2026.08.01/GeoLite2-City.mmdb";
      hash = "sha256-bmaEyrBOu6EMHqn0pEMXXKD/CA4lXoT57wNQUXWCZX4=";
    };
  };
  geolite2-country = {
    pname = "geolite2-country";
    version = "2026.08.01";
    src = fetchurl {
      url = "https://github.com/P3TERX/GeoLite.mmdb/releases/download/2026.08.01/GeoLite2-Country.mmdb";
      hash = "sha256-0Y8TkBT/Md0LAF4WoVWEnA0mtZxl2ceRaKeA2igYk2Q=";
    };
  };
}
